export enum prueba {
  CONSULTANT = 0,
  DISTRIBUTOR = 1,
  CONSULTANT_NO_RFC = 2,
}

export enum ENotificationType {
  "APPOINTMENT_ACCEPTED" = "APPOINTMENT_ACCEPTED",
  "APPOINTMENT_REJECTED" = "APPOINTMENT_REJECTED",
  "NEW_REQUEST" = "NEW_REQUEST",
  "MESSAGE" = "MESSAGE",
}
